### ISSUE TITLE
debain can not booting only show NEXELL

### ISSUE THREAD

**Issue by lecheel** [friendlyarm/sd-fuse_nanopi2#1]
following the instruction ./fusing.sh /dev/sdc debian 
screen freeze on NEXELL any help
debian jessie image
c65332445e5b6d87a7a166926dfcbbba  debian-jessie-images.tgz

**Comment by friendlyarm** [comment]
Sorry to hear you encounter this issue. 
We're uploading the lastest image (debian-jessie-images.tgz), and before we are done you can try:
http://wiki.friendlyarm.com/wiki/index.php/NanoPi_2#Under_Windows

**Comment by lecheel** [comment]
in debian image is it the right way show log in hdmi monitor??
in /etc/systemd/system.conf
uncomment
#ShowStatus=yes

**Comment by lecheel** [comment]
the problem which cause by SD 16G TF card, using 4GB SD card is working
