### ISSUE TITLE
Where is the code for `tools/fw_setenv`?

### ISSUE THREAD

**Issue by vinipsmaker** [friendlyarm/sd-fuse_nanopi2#2]
Hi, could `tools/fw_setenv` maybe replaced by a script? I really dislike running random binaries from my system.

**Comment by friendlyarm** [comment]
Source code:
https://github.com/friendlyarm/uboot_nanopi2/tree/nanopi2-lollipop-mr1/tools/env

**Comment by vinipsmaker** [comment]
Thanks
