### ISSUE TITLE
用于 NanoPi2的系统镜像无法启动

### ISSUE THREAD

**Issue by Gsonovb** [friendlyarm/sd-fuse_nanopi2#3]
用于Nanopi2 的最新系统镜像无法启动，
我下载今年1月份的镜像

s5p4418-eflasher-lubuntu-desktop-xenial-4.4-armhf-20190128.img.zip
s5p4418-eflasher-friendlycore-xenial-4.4-armhf-20190128.img.zip

刷机后只显示一个画面，然后就卡了
根据源代码自己编译，也是一样。

**Comment by friendlyarm** [comment]
旧版本的nanopi2需要切换到kernel3.4的分支

**Comment by KruziikG** [comment]
@friendlyarm 请问下是因为旧版本的nanopi 2/nanopi2 fire和后面s5p4418的硬件有变化，所以只能用3.4的内核吗？
