### ISSUE TITLE
文件下载没有权限

### ISSUE THREAD

**Issue by DabinChen** [friendlyarm/sd-fuse_nanopi2#4]
Forbidden
You don't have permission to access /dvdfiles/S5P4418/rootfs/rootfs-friendlycore-20190603.tgz on this server.
Apache/2.4.18 (Ubuntu) Server at 112.124.9.243 Port 80

**Comment by friendlyarm** [comment]
多谢反馈，已经修复了，同时建议你从网盘下载，以获得较快的下载速度

**Comment by DabinChen** [comment]
你好！
          我按照最新的git上的方法定制rootfs，制作好镜像烧写时报错，rootfs太大，我的rootfs镜像文件是2.4G





---原始邮件---
发件人: "friendlyarm"<notifications@github.com>
发送时间: 2019年6月27日(星期四) 晚上10:13
收件人: "friendlyarm/sd-fuse_s5p4418"<sd-fuse_s5p4418@noreply.github.com>;
抄送: "DabinChen"<1343053316@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [friendlyarm/sd-fuse_s5p4418] 文件下载没有权限 (#4)



多谢反馈，已经修复了，同时建议你从网盘下载，以获得较快的下载速度
