### ISSUE TITLE
rootfs.img too big

### ISSUE THREAD

**Issue by DabinChen** [friendlyarm/sd-fuse_nanopi2#5]
我重新制作了镜像，定制了rootfs，rootfs大小是2.38G，烧写报错文件太大。

**Comment by friendlyarm** [comment]
请参考build-rootfs-img.sh，现在会自动计算rootfs内容的大小，不再需要手动指定大小

**Comment by DabinChen** [comment]
你好！
       我按照https://github.com/friendlyarm/sd-fuse_s5p4418编译了kernel，制作了emmc烧写镜像，报错无法烧写rootfs，我没有对你们的文件做任何的修改。没有编译kernel时是可以烧写的。






------------------ 原始邮件 ------------------
发件人: "friendlyarm"<notifications@github.com>;
发送时间: 2019年8月23日(星期五) 上午10:16
收件人: "friendlyarm/sd-fuse_s5p4418"<sd-fuse_s5p4418@noreply.github.com>;
抄送: "QQ网名"<1343053316@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [friendlyarm/sd-fuse_s5p4418] rootfs.img too big (#5)




请参考build-rootfs-img.sh，现在会自动计算rootfs内容的大小，不再需要手动指定大小
